version: '3.8'

services:
  web:
    build: .
    ports:
      - "80:80"
    restart: unless-stopped

  server:
    build: 
      context: .
      dockerfile: Dockerfile.server
    ports:
      - "3000:3000"
    restart: unless-stopped
    environment:
      - TELEGRAM_BOT_TOKEN=7714564597:AAHA1_lTI6tyyW6wf35lhw0q7HaT3awcd2s
      - TELEGRAM_CHAT_ID=-4654902560